### ISSUE TITLE
exception for the example

### ISSUE THREAD

**Issue by guanqun** [Fuyukai/asyncwebsockets#2]
When I run the example, it raises the exception:

```
....
  File "~/lib/python3.6/site-packages/trio/_ssl.py", line 416, in _check_status
    raise ClosedStreamError
trio.ClosedStreamError
```

Is this the expected behavior?

I'm using trio 0.3.0

```
import multio

from asyncwebsockets.client import connect_websocket
from asyncwebsockets.ws import WebsocketConnectionEstablished, WebsocketBytesMessage


async def test():
    sock = await connect_websocket("wss://echo.websocket.org", reconnecting=False)
    async for message in sock:
        print("Event received", message)
        if isinstance(message, WebsocketConnectionEstablished):
            await sock.send_message(b"test")

        elif isinstance(message, WebsocketBytesMessage):
            print("Got response:", message.data)
            await sock.close(code=1000, reason="Thank you!")


multio.init("trio")
multio.run(test)
```

**Comment by Fuyukai** [comment]
Well, I've found that usually it deadlocks instead of erroring, so that's new.

Unfortunately, Trio doesn't have a "nice" error hierachy so catching these at the lib-level isn't that possible yet, but it's planned, as well as a general bit of rewriting to make the connection more stable.

**Comment by belm0** [comment]
curio case fails too:

```
Event received <asyncwebsockets.ws.WebsocketConnectionEstablished object at 0x106294160>
Event received <asyncwebsockets.ws.WebsocketBytesMessage object at 0x10629dcf8>
Got response: b'test'
Task Crash: Task(id=2, name='test', state='TERMINATED')
Traceback (most recent call last):
...
OSError: [Errno 9] Bad file descriptor
```
> Unfortunately, Trio doesn't have a "nice" error hierachy so catching these at the lib-level isn't that possible 
Do you mean that multio doesn't have an error hierarchy abstraction yet?

For Trio case looks like something similar was addressed in trio-amqp (https://github.com/python-trio/trio-amqp/commit/9599b6e32cc80e576eb23404ad1f83e20b9f657c, https://github.com/python-trio/trio-amqp/commit/3f12e223ec05719352d4578b140269b94d9e9578).

**Comment by belm0** [comment]
I can make both Trio and Curio cases work as follows (obviously bad due to trio dependency).

Should multio abstract the ClosedResourceError?  Should multio be suppressing the exception?  Or this is the wrong approach altogether?

```diff
--- a/asyncwebsockets/ws.py
+++ b/asyncwebsockets/ws.py
@@ -5,6 +5,7 @@ from io import BytesIO, StringIO
 from typing import Tuple, Union

 import multio
+import trio
 from wsproto import events
 from wsproto.connection import ConnectionType, WSConnection

@@ -116,7 +117,10 @@ class ClientWebsocket(object):
         buf_text = StringIO()

         while True:
-            data = await self.sock.recv(4096)
+            try:
+                data = await self.sock.recv(4096)
+            except (trio.ClosedResourceError, OSError):
+                return
             self.state.receive_bytes(data)

             # do ping/pongs if needed
```

**Comment by belm0** [comment]
with latest commit, trio shutdown is clean

curio is failing earlier than shutdown

```
ask Crash: Task(id=2, name='test', state='TERMINATED')
Traceback (most recent call last):
  File "/Users/john/.pyenv/versions/3.6.5/lib/python3.6/site-packages/curio/kernel.py", line 736, in _run_coro
    trap = current._send(current.next_value)
  File "/Users/john/.pyenv/versions/3.6.5/lib/python3.6/site-packages/curio/task.py", line 167, in _task_runner
    return await coro
  File "test.py", line 5, in test
    async with open_websocket('wss://echo.websocket.org') as sock:
  File "/Users/john/.pyenv/versions/3.6.5/lib/python3.6/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/Users/john/.pyenv/versions/3.6.5/lib/python3.6/site-packages/curio/meta.py", line 409, in _init_async_gen
    raise RuntimeError("Async generator with async finalization must be wrapped by\n"
RuntimeError: Async generator with async finalization must be wrapped by
async with curio.meta.finalize(agen) as agen:
    async for n in agen:
         ...
See PEP 533 for further discussion.
```

```
import multio
from asyncwebsockets.client import open_websocket

async def test():
    async with open_websocket('wss://echo.websocket.org') as sock:
        await sock.send('test')
        message = await sock.next_event()
        print(message)


multio.init('curio')
multio.run(test)
```

**Comment by Fuyukai** [comment]
Should be fixed now.
